# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e7160b3e208336d33ebb28fb240ef4d14438d0153bfb0b9c158ebe0c47ab916b005ade0411b8e3a0e83e88f68b7015c1a03fa47f4579c29873ef84032019e1c

test:
  secret_key_base: 52d7d3b2e34147c814d5454e5399e34b9e6c8c1edb3eb714367b20488a2ba9cd686ed94fa51cc5bab084ad087c4a20d2c79a5ee1523404496ecc2fff282331e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
